name: aug_kl_divs
augmentations: 
  RandomResize:
    use: true
    size: [256,256]
  RandomRotation: 
    use: true
    degrees: 45
  RandomAffine:
    use: true
    degrees: 30
    traslate: [0.1, 0.1]
    scale: [0.75, 1.25]
  GaussianNoise:
    use: true
    noise_levels: [10.0]
mink:
  ratio: [0, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]


