name: min_k_renyi_divergence_2
alpha: 2
suffix: renyi_2
ratio:
  - 0
  - 0.05
  - 0.1
  - 0.2
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
augmentation_accumilator: ["avg","max","none"]             #average or max
augmentation_setting_version_accumilator: ["avg","max","none"]      #average or max
  