name: min_k_renyi_05_kl_div
alpha: 2
suffix: renyi_2
ratio:
  - 0
  - 0.05
  - 0.1
  - 0.2
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
augmentation_accumilator: avg             #average or max
augmentation_setting_version_accumilator: avg     #average or max
  